name: Publish to Maven

on:
  release:
    types: [ created ]
#  push:
#    branches: [ "main" ]
#    tags:
#      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #          MAVEN_USERNAME: ${{ secrets.MVN_USERNAME }}
        #          MAVEN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
        #          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        #          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
        #          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
        run: ./gradlew publish # -Dgit.tag="${{ github.ref_name }}" # -Dgit.ref="${{ github.ref }}" -Dgit.branch="${{ github.ref }}"
